### ISSUE TITLE
android studioの内容がEmulaterに反映されない件について

### ISSUE THREAD

**Issue by Yoshida-koshi** [Yoshida-koshi/myapp3#1]
![2021-07-03](https://user-images.githubusercontent.com/85224998/124346108-ff44f580-dc17-11eb-8023-81e74c531a9e.png)
ペアの人がflutter doctorの実行内容を僕に聞いてきたので、powershellでflutter doctorを実行してみるとエラーが発生していたので、ターミナルでも同じようにflutter doctorを実行したところ、powershellで実行した時と同じエラーが発生しました。エラーの内容は写真の通りです。エラー文に基づいてhttps://stackoverflow.com/questions/3623351/git-subtree-pull-says-that-the-working-tree-has-modifications-but-git-status-sa　　https://stackoverflow.com/questions/55470780/error-on-line-55-column-4-of-pubspec-yaml-expected-a-key-while-parsing-a-block
の２つのサイトに沿ってやってみたのですが全くできません。どなたか助けてくださると嬉しいです。

**Comment by Yoshida-koshi** [comment]
![2021-06-28](https://user-images.githubusercontent.com/85224998/124346388-8050bc80-dc19-11eb-8ddc-1bd839f960b9.png)
ちなみにgit statusは上の写真の通りです。

**Comment by taitai9847** [comment]
@Yoshida-koshi 
エラー文にも書いてあるのですが、以下は実行してみました？
`flutter update-packages --force-upgrade`

**Comment by mcz9mm** [comment]
cloneしてビルドしてみたけど問題なく実行できたので環境の問題かも

<img width="1787" alt="スクリーンショット 2021-07-05 11 30 58" src="https://user-images.githubusercontent.com/11751495/124410045-88793b00-dd84-11eb-888c-cf0449e19050.png">

**Comment by mcz9mm** [comment]
これ試した結果教えて
> @Yoshida-koshi
> エラー文にも書いてあるのですが、以下は実行してみました？
> `flutter update-packages --force-upgrade`

**Comment by Yoshida-koshi** [comment]
![2021-07-07](https://user-images.githubusercontent.com/85224998/124694316-fb68ea00-df1b-11eb-872c-158de9fc0c05.png)
flutter update-packages --force-upgradeを実行した結果です。

**Comment by mcz9mm** [comment]
同じような現象が起きてる人いるっぽい

https://github.com/flutter/flutter/issues/31767

**Comment by mcz9mm** [comment]
Flutterを再度インストールし直してみたりしてもよさそう

**Comment by mcz9mm** [comment]
これをみる感じこのリポジトリをクローンし直せばうまくいきそう
https://github.com/flutter/flutter/issues/25056

**Comment by taitai9847** [comment]
Flutter再インストールがベターかもしれないですね。

**Comment by Yoshida-koshi** [comment]
![2021-07-07 (1)](https://user-images.githubusercontent.com/85224998/124723678-40097b00-df46-11eb-8c9e-d0b4acbbfbfc.png)
単純にflutter-sdkを最新版にしていませんでした。最新版のflutter-sdkをインストールしたら動きました。
ご協力ありがとうございました。
